apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.product }}
  labels:
    app: {{ .Values.product }}
    product: {{ .Values.product }}
    managed-by: argocd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.product }}
  template:
    metadata:
      labels:
        app: {{ .Values.product }}
        product: {{ .Values.product }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: {{ .Values.message | quote }}
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
