apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.product }}
  labels:
    app: {{ .Values.product }}
    product: {{ .Values.product }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.product }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
